name: Alpha
description: Alphs template for Jekyll
baseurl: '/Alpha-theme'

url: 'http://test-theme.github.io/Alpha-theme/'

# PAGINATION
gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"
